on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**" # matches every branch
name: "Node.js Lint, Tests and Coverage"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm i npm@8 -g
      - run: npm ci
      - run: npm run lint
      - run: npm run format
