name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: npm ci and build
        env:
          CI: false
          PUBLIC_URL: "/${{ github.event.repository.name }}"
          REACT_APP_GRAPHQL_API_ENDPOINT: "https://node-beta-1.fuel.network/graphql"
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
